import time
import openai
import logging

from lanlab.models.model import Model, ModelConfig
from lanlab.tools.dict_tools import SafeDict
from lanlab.data_management.batch.sequence import Sequence
from lanlab.data_management.data.segment import Segment

class UnsplittableQuery(Exception):
    def __init__(self):
        super().__init__()
        self.message = "The query cannot be found in the token list. This could either be due to a bug so that the query and the list of tokens mismatch or it could be due to a retokenization issue (if A is a list of token : tokenize(detokenize(A)) != A)."

def split_token_list(l,query):
    #Split the token list l into two lists, the first one containing the tokens that are in the query and the second one containing the rest of the tokens
    s = ""
    if s == query:
        return l
    for i in range(len(l)):
        s += l[i]
        if s == query:
            return l[:i+1],l[i+1:]
    raise UnsplittableQuery

def chat_to_str(l):
    #Convert a chat completion from openai to a string
    s = ""
    for i,d in enumerate(l):
        k,v = d['role'],d['content']
        s += k.upper()+": "+v
        if i < len(l)-1:
            s += '\n'
    return s

def sequence_from_OPENAICompletion(answer):
    seg = Segment()
    seg["model"] = answer['model']
    seg['text'] = answer['choices'][0]['text']
    seg['tokens'] = answer['choices'][0]['logprobs']['tokens']
    seg['logp'] = answer['choices'][0]['logprobs']['token_logprobs']
    seg['top_logp'] = [dict(e) if not(e is None) else None for e in answer['choices'][0]['logprobs']['top_logprobs']]
    seg['finish_reason'] = answer['choices'][0]['finish_reason']
    seg['origin'] = 'assistant'
    if 'logits' in answer['choices'][0]['logprobs']:
        seg['logits'] = answer['choices'][0]['logprobs']['logits']
    return Sequence(l=[seg])

def sequence_from_OPENAIChat(answer):
    seg = Segment()
    seg["model"] = answer['model']
    seg['text'] = answer['choices'][0]['message']['content']
    seg['origin'] = answer['choices'][0]['message']['role']
    seg['finish_reason'] = answer['choices'][0]['finish_reason']
    return Sequence(l=[seg])

def sequence_to_OPENAIChat(seq):
    #Convert a sequence to a list of dictionaries that can be used as input for the chat API
    l = []
    for segment in seq:
        d = {}
        d['role'] = segment['origin']
        d['content'] = segment['text']
        l.append(d)
    return l

def OPENAIretry(f):
    """This decorator is used to retry a function if it raises an APIError or a RateLimitError."""
    error_count = 0
    error_count_max = 5
    def g(*args,**kwargs):
        try:
            return f(*args,**kwargs)
        except openai.error.APIError:
            logging.error('[openai API Error] : Retrying in 1 sec')
            error_count += 1
            if error_count > error_count_max:
                logging.error('Too many APIErrors : the process will stop')
                assert False
            time.sleep(1)
            return g(*args,**kwargs)
        except openai.error.RateLimitError:
            logging.info('[openai RateLimitError] : Retrying in 1 min')
            time.sleep(62)
            return g(*args,**kwargs)
    return g
        

class GPT(Model):
    """This class is a wrapper for the OpenAI GPT-3 API. It is used to send requests to the API and to get the responses."""
    def __init__(self,config=None):
        super().__init__(config)
        self._engine = None

        from decouple import config
        openai.api_key = config('OPENAI_API_KEY')

    @property
    def name(self):
        raise NotImplementedError

    @property
    def engine(self):
        return NotImplementedError

    @OPENAIretry
    def complete(self,sequence,config):
        raise NotImplementedError
    
    @OPENAIretry
    def read(self,sequence,config):
        """ Reads the given sequence, do not generate an additional segment but updates the logp and top_logp of all the segments in the sequence"""
        raise NotImplementedError

class ChatGPTConfig(ModelConfig):
    pass

class ChatGPT(GPT):
    """This class is used to interact with the chat models of OpenAI.'"""
    @property
    def config_class(self):
        return ChatGPTConfig
    @OPENAIretry
    def complete(self,sequence,config=None):
        """ Complete the given sequence adding a segment generated by the LLM to it"""
        if config is None:
            config = self.config
        messages = sequence_to_OPENAIChat(sequence)
        answer = openai.ChatCompletion.create(
            messages=messages,
            **config.to_dict(),
            model=self.engine)
        segment = sequence_from_OPENAIChat(answer)
        return sequence + segment
    @OPENAIretry
    def read(self,sequence,config=None):
        #Not available on this family of model
        raise NotImplementedError

class CompletionGPTConfig(ModelConfig):
    """ Class that implements top_logprobs parameter """
    def __init__(self):
        super().__init__()
        self.add_key('logprobs',5)

class CompletionGPT(GPT):
    """This class is used to interact with the completion models of OpenAI from the completion module. These models do not take a sequence as input but the prompt (str) to be completed directly.'"""
    @property
    def config_class(self):
        return CompletionGPTConfig
    @OPENAIretry
    def complete(self,sequence,config=None):
        if config is None:
            config = self.config
        prompt = str(sequence)
        answer = openai.Completion.create(
            prompt=prompt,
            **config.to_dict(),
            engine=self.engine,
            logprobs=5)
        segment = sequence_from_OPENAICompletion(answer)
        return sequence + segment
    @OPENAIretry
    def read(self,sequence,config=None):
        if config is None:
            config = self.config
        prompt = str(sequence)
        config['max_tokens'] = 0
        answer = openai.Completion.create(
            prompt=prompt,
            **config.to_dict(),
            engine=self.engine,
            logprobs=5,
            echo=True)
        segment = sequence_from_OPENAICompletion(answer)
        return Sequence([segment])
        


#--------------------------------------------
#CompletionGPT
#--------------------------------------------

class AD(CompletionGPT):
    @property
    def engine(self):
        return 'ada'
    @property
    def name(self):
        return 'AD'

class AD1(CompletionGPT):
    @property
    def engine(self):
        return 'text-ada-001'
    @property
    def name(self):
        return 'AD1'

class BB(CompletionGPT):
    @property
    def engine(self):
        return 'babbage'
    @property
    def name(self):
        return 'BB'

class BB1(CompletionGPT):
    @property
    def engine(self):
        return 'text-babbage-001'
    @property
    def name(self):
        return 'BB1'

class CU(CompletionGPT):
    @property
    def engine(self):
        return 'curie'
    @property
    def name(self):
        return 'CU'

class CU1(CompletionGPT):
    @property
    def engine(self):
        return 'text-curie-001'
    @property
    def name(self):
        return 'CU1'

class DV(CompletionGPT):
    @property
    def engine(self):
        return 'davinci'
    @property
    def name(self):
        return 'DV'

class DVB(CompletionGPT):
    @property
    def engine(self):
        return 'davinci-instruct-beta'
    @property
    def name(self):
        return 'DVB'

class DV1(CompletionGPT):
    @property
    def engine(self):
        return 'text-davinci-001'
    @property
    def name(self):
        return 'DV1'

class CDV2(CompletionGPT):
    @property
    def engine(self):
        return 'code-davinci-002'
    @property
    def name(self):
        return 'CDV2'

class DV2(CompletionGPT):
    @property
    def engine(self):
        return 'text-davinci-002'
    @property
    def name(self):
        return 'DV2'

class DV3(CompletionGPT):
    @property
    def engine(self):
        return 'text-davinci-003'
    @property
    def name(self):
        return 'DV3'
    
#--------------------------------------------
#ChatGPT
#--------------------------------------------

class GPT35(ChatGPT):
    @property
    def engine(self):
        return 'gpt-3.5-turbo'
    @property
    def name(self):
        return 'GPT35'
    
#Seems like it is the same as GPT35
class GPT35B(ChatGPT):
    @property
    def engine(self):
        return 'gpt-3.5-turbo-0301'
    @property
    def name(self):
        return 'GPT35B'
    
class GPT4(ChatGPT):
    @property
    def engine(self):
        return 'gpt-4'
    @property
    def name(self):
        return 'GPT4'
    
#Seems like it is the same as GPT4
class GPT4B(ChatGPT):
    @property
    def engine(self):
        return 'gpt-4-0314'
    @property
    def name(self):
        return 'GPT4B'

def get_openai_model_classes():
    return [AD,AD1,BB,BB1,CU,CU1,DV,DVB,DV1,CDV2,DV2,DV3,GPT35,GPT4]